[agent]
  interval = "15s"
  omit_hostname = true

[[inputs.docker]]
  endpoint = "tcp://socket-proxy:2375"
  docker_label_include = ["com.docker.compose.project"]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
